### PR TITLE
ease and modernise installation a bit

### PR DESCRIPTION
**Pull request by blex-max**

### CODE REVIEW

**Review by davidrajones — COMMENTED** [review]
Love the commit message.... 

Do you want to be linking to master version of linasm or a particular version (commit ref I guess given there's no tagging)? Other libraries installed are versioned.

**Comment by blex-max** [comment]
Hello! Thanks for taking a look. Well, what should have been trivial changes lead to bizarre rabbitholes around make behaviour. It's all useful experience I guess. Good point, I will change to the most recent commit

**Comment by blex-max** [comment]
Oh also there was a little associated commentary/background with this PR but it was on internal slack, I didn't know you would see the PR - the tool relies on linasm but doesn't actually reference it in the makefile or setup so compiliation couldn't be achieved as written

**Comment by blex-max** [comment]
fixed

**Pull request merged**
